In [1]:
import numpy as np 
import pandas as pd
import pandas as pd # to import csv and for data manipulation
import matplotlib.pyplot as plt # to plot graph
import seaborn as sns # for intractve graphs
import numpy as np # for linear algebra
import datetime # to dela with date and time
%matplotlib inline
from sklearn.preprocessing import StandardScaler # for preprocessing the data
from sklearn.ensemble import RandomForestClassifier # Random forest classifier
from sklearn.tree import DecisionTreeClassifier # for Decision Tree classifier
from sklearn.svm import SVC # for SVM classification
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split # to split the data
from sklearn.cross_validation import KFold # For cross vbalidation
from sklearn.model_selection import GridSearchCV # for tunnig hyper parameter it will use all combination of given parameters
from sklearn.model_selection import RandomizedSearchCV # same for tunning hyper parameter but will use random combinations of parameters
from sklearn.metrics import confusion_matrix,recall_score,precision_recall_curve,auc,roc_curve,roc_auc_score,classification_report
import warnings
warnings.filterwarnings('ignore')

/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [97]:
data = pd.read_csv("/home/simmi/Downloads/res_purchase_card_(pcard)_fiscal_year_2014_3pcd-aiuu.csv",header = 0)

In [98]:
data.info()
data.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442458 entries, 0 to 442457
Data columns (total 11 columns):
Year-Month                      442458 non-null int64
Agency Number                   442458 non-null int64
Agency Name                     442458 non-null object
Cardholder Last Name            442458 non-null object
Cardholder First Initial        442458 non-null object
Description                     442458 non-null object
Amount                          442458 non-null float64
Vendor                          442458 non-null object
Transaction Date                442458 non-null object
Posted Date                     442458 non-null object
Merchant Category Code (MCC)    442458 non-null object
dtypes: float64(1), int64(2), object(8)
memory usage: 37.1+ MB

,Year-Month,Agency Number,Agency Name,Cardholder Last Name,Cardholder First Initial,Description,Amount,Vendor,Transaction Date,Posted Date,Merchant Category Code (MCC)
0,201307,1000,OKLAHOMA STATE UNIVERSITY,Mason,C,GENERAL PURCHASE,890.00,NACAS,07/30/2013 12:00:00 AM,07/31/2013 12:00:00 AM,CHARITABLE AND SOCIAL SERVICE ORGANIZATIONS
1,201307,1000,OKLAHOMA STATE UNIVERSITY,Mason,C,ROOM CHARGES,368.96,SHERATON HOTEL,07/30/2013 12:00:00 AM,07/31/2013 12:00:00 AM,SHERATON
2,201307,1000,OKLAHOMA STATE UNIVERSITY,Massey,J,GENERAL PURCHASE,165.82,SEARS.COM 9300,07/29/2013 12:00:00 AM,07/31/2013 12:00:00 AM,DIRCT MARKETING/DIRCT MARKETERS--NOT ELSEWHERE...
3,201307,1000,OKLAHOMA STATE UNIVERSITY,Massey,T,GENERAL PURCHASE,96.39,WAL-MART #0137,07/30/2013 12:00:00 AM,07/31/2013 12:00:00 AM,"GROCERY STORES,AND SUPERMARKETS"
4,201307,1000,OKLAHOMA STATE UNIVERSITY,Mauro-Herrera,M,HAMMERMILL COPY PLUS COPY EA,125.96,STAPLES DIRECT,07/30/2013 12:00:00 AM,07/31/2013 12:00:00 AM,"STATIONERY, OFFICE SUPPLIES, PRINTING AND WRIT..."
5,201307,1000,OKLAHOMA STATE UNIVERSITY,Mauro-Herrera,M,GENERAL PURCHASE,394.28,KYOCERA DOCUMENT SOLUTION,07/29/2013 12:00:00 AM,07/31/2013 12:00:00 AM,"OFFICE, PHOTOGRAPHIC, PHOTOCOPY, AND MICROFILM..."
6,201307,1000,OKLAHOMA STATE UNIVERSITY,Mays,B,GENERAL PURCHASE,19.87,WAL-MART #0137,07/30/2013 12:00:00 AM,07/31/2013 12:00:00 AM,"GROCERY STORES,AND SUPERMARKETS"
7,201307,1000,OKLAHOMA STATE UNIVERSITY,Mays,B,GENERAL PURCHASE,10.10,DAYLIGHT DONUTS,07/29/2013 12:00:00 AM,07/31/2013 12:00:00 AM,FAST FOOD RESTAURANTS
8,201307,1000,OKLAHOMA STATE UNIVERSITY,McCarthy,D,GENERAL PURCHASE,142.60,UFIRST LAUNDRY SVCS,07/30/2013 12:00:00 AM,07/31/2013 12:00:00 AM,"MENS, WOMENS AND CHILDRENS UNIFORMS AND COMMER..."
9,201307,1000,OKLAHOMA STATE UNIVERSITY,McClurg,L,AT&T SERVICE PAYMENT ITM,29.99,AT&T DATA,07/30/2013 12:00:00 AM,07/31/2013 12:00:00 AM,TELECOMMUNICATION SERVICES
10,201307,1000,OKLAHOMA STATE UNIVERSITY,McGowin,R,GENERAL PURCHASE,278.23,RANDY'S FOODS,07/29/2013 12:00:00 AM,07/31/2013 12:00:00 AM,FREEZER AND LOCKER MEAT PROVISIONERS
11,201307,1000,OKLAHOMA STATE UNIVERSITY,McKee,P,GENERAL PURCHASE,127.80,DEARINGER PRINTING & TROP,07/30/2013 12:00:00 AM,07/31/2013 12:00:00 AM,MISCELLANEOUS AND SPECIALTY RETAIL STORES
12,201307,1000,OKLAHOMA STATE UNIVERSITY,McLemore,A,GENERAL PURCHASE,572.27,GIDDINGS MACHINE CO.,07/30/2013 12:00:00 AM,07/31/2013 12:00:00 AM,"COMMERCIAL EQUIPMENT, NOT ELSEWHERE CLASSIFIED"
13,201307,1000,OKLAHOMA STATE UNIVERSITY,McMurry,S,50-LB PLAY SAND BAG|20 QT POTTING SOIL TIMBERL EA,12.90,LOWES #00241,07/30/2013 12:00:00 AM,07/31/2013 12:00:00 AM,HOME SUPPLY WAREHOUSE STORES
14,201307,1000,OKLAHOMA STATE UNIVERSITY,Meints,K,GENERAL PURCHASE,445.00,OK DEPT OF VO-TECH ED,07/30/2013 12:00:00 AM,07/31/2013 12:00:00 AM,GOVERNMENT SERVICES--NOT ELSEWHERE CLASSIFIED
15,201307,1000,OKLAHOMA STATE UNIVERSITY,Mohiuddin,A,GENERAL PURCHASE,452.91,TFS THERMOASHEVILLE,07/31/2013 12:00:00 AM,07/31/2013 12:00:00 AM,DENTAL/LABORATORY/MEDICAL/OPHTHALMIC HOSP EQIP...
16,201307,1000,OKLAHOMA STATE UNIVERSITY,Mohiuddin,I,GENERAL PURCHASE,2425.00,WESTERN EQUIPMENT ALVA,07/29/2013 12:00:00 AM,07/31/2013 12:00:00 AM,HARDWARE STORES
17,201307,1000,OKLAHOMA STATE UNIVERSITY,Mohiuddin,I,GENERAL PURCHASE,2425.00,WESTERN EQUIPMENT ALVA,07/29/2013 12:00:00 AM,07/31/2013 12:00:00 AM,HARDWARE STORES
18,201307,1000,OKLAHOMA STATE UNIVERSITY,Mollenhauer,R,GENERAL PURCHASE,7.63,HOBBY-LOBBY #0005,07/29/2013 12:00:00 AM,07/31/2013 12:00:00 AM,"HOBBY,TOY,AND GAME STORES"
19,201307,1000,OKLAHOMA STATE UNIVERSITY,MONTGOMERY,R,GENERAL PURCHASE,18.97,WAL-MART #0121,07/30/2013 12:00:00 AM,07/31/2013 12:00:00 AM,"GROCERY STORES,AND SUPERMARKETS"

In [28]:
# The overall distribution of the amounts as a histogram
distribution = data.groupby(by=['Merchant Category Code (MCC)'])['Amount'].sum()
distribution.head()

# distribution["Merchant Category Code (MCC)"].value_counts().plot.bar()

# plt.show()

Merchant Category Code (MCC)
                                                   883.08
ACCOUNTING,AUDITING AND BOOKKEEPING SERVICES     78360.01
ADVANTAGE RENT A CAR                               585.83
ADVERTISING SERVICES                            756053.31
AER LINGUS                                        5305.61
Name: Amount, dtype: float64

In [11]:
# s = data['Vendor'].groupby(data['Amount']).value_counts()
# print s.groupby(level=0).nlargest(5)
# the top-k most popular vendors by number of transactions, 
data['Vendor'].value_counts().nlargest(5)

STAPLES                      14842
AMAZON MKTPLACE PMTS         12197
WW GRAINGER                  12076
Amazon.com                   10766
BILL WARREN OFFICE PRODUC     4479
Name: Vendor, dtype: int64

In [16]:
# the top-k highest categories by sum of amounts.
data.groupby(by=['Merchant Category Code (MCC)'])['Amount'].sum().nlargest(5)

Merchant Category Code (MCC)
                                                            883.08
ACCOUNTING,AUDITING AND BOOKKEEPING SERVICES              78360.01
ADVANTAGE RENT A CAR                                        585.83
ADVERTISING SERVICES                                     756053.31
AER LINGUS                                                 5305.61
AEROLINEAS ARGENTINAS                                       912.30
AEROMEXICO                                                 1447.76
AGRICULTURAL COOPERATIVES                                494016.01
AIR BERLIN                                                 4396.70
AIR CANADA                                                 7582.88
AIR CHINA                                                 16251.83
AIR CONDITIONING AND REFRIGERATION REPAIR SHOPS          116602.19
AIR FRANCE                                                25070.08
AIR INDIA                                                  8842.13
AIR NEW ZEALAND LTD. INTERNATIONAL                         6422.40
AIRLINES AND AIR CARRIERS                                178710.12
AIRPORTS,FLYING FIELDS,AND AIRPORT TERMINALS              10364.92
AIRTRAN AIRWAYS                                           17120.90
ALAMO RENT-A-CAR                                           1001.56
ALASKA AIRLINES INC.                                      17406.73
ALITALIA                                                   1954.00
ALOFT HOTELS                                               4653.75
AMBULANCE SERVICES                                           35.00
AMERICAN AIRLINES                                       5296951.04
AMERICAS BEST VALUE INN                                    5059.48
AMERICINN                                                  5023.95
AMUSEMENT PRKS,CIRCUSES,CARNIVLS,AND FORTUNE TELLERS      40656.48
ANTIQUE SHOPS                                              3380.32
AQUARIUMS,SEAQUARIUMS AND DOLPHINARIUMS                   13440.85
ARCHITECTURAL,ENGINEERING,AND SURVEYING SERVICES         213564.43
                                                           ...
TROPICANA RESORT AND CASINO                                1808.80
TRUCK AND UTILITY TRAILER RENTALS                         55425.14
TURK HAVA YOLLARI (THY)                                   17096.08
TYPESETTING, PLATE MAKING & RELATED SERVICES              50638.35
TYPEWRITER STORES-SALES,SERVICE,RENTALS                    3747.81
UNITED AIRLINES                                         1735964.32
USAIRWYS                                                 101400.46
USED MERCHANDISE AND SECONDHAND STORES                    -7290.22
UTILITIES - ELECTRIC,GAS,WATER,SANITARY                 3018684.34
VAGABOND HOTELS                                             492.05
VARIETY STORES                                            66356.29
VDARA                                                       902.72
VETERINARY SERVICES                                      151465.51
VIDEO AMUSEMENT GAME SUPPLIES                              1485.23
VIDEO GAME ARCADES AND ESTABLISHMENTS                      3787.73
VIRGIN AMERICA                                              198.90
VIRGIN ATLANTIC                                             231.50
W HOTELS                                                  17189.39
WALDORF                                                     268.33
WATCH,CLOCK AND JEWELRY REPAIR SHOPS                       5530.11
WELDING SERVICES                                         173909.83
WESTIN HOTELS                                             99313.96
WESTJET AIRLINES                                            264.78
WHOLESALE CLUBS                                           10862.66
WIG AND TOUPEE SHOPS                                       1085.52
WOMEN'S ACCESSORY AND SPECIALTY STORES                    37305.66
WOMEN'S READY-TO-WEAR STORES                              47392.13
WRECKING AND SALVAGE YARDS                                 1205.00
WYNDHAM HOTELS                                            58266.06
WYNN LAS VEGAS                                             3797.92
Name: Amount, Length: 435, dtype: float64

Merchant Category Code (MCC)
DENTAL/LABORATORY/MEDICAL/OPHTHALMIC HOSP EQIP AND SUP.    11004961.34
INDUSTRIAL SUPPLIES NOT ELSEWHERE CLASSIFIED               10846920.22
COMPUTERS, COMPUTER PERIPHERAL EQUIPMENT, SOFTWARE         10091600.76
COMMERCIAL EQUIPMENT, NOT ELSEWHERE CLASSIFIED              8139120.69
MISCELLANEOUS AND SPECIALTY RETAIL STORES                   5563077.11
Name: Amount, dtype: float64

In [36]:
new_data = data.filter(['Cardholder Last Name','Cardholder First Initial','Merchant Category Code (MCC)','Amount'], axis=1)
# new_data.head()
# new_data.groupby(by=['Merchant Category Code (MCC)'])['Amount'].sum().nlargest(10)

Merchant Category Code (MCC)
DENTAL/LABORATORY/MEDICAL/OPHTHALMIC HOSP EQIP AND SUP.      11004961.34
INDUSTRIAL SUPPLIES NOT ELSEWHERE CLASSIFIED                 10846920.22
COMPUTERS, COMPUTER PERIPHERAL EQUIPMENT, SOFTWARE           10091600.76
COMMERCIAL EQUIPMENT, NOT ELSEWHERE CLASSIFIED                8139120.69
MISCELLANEOUS AND SPECIALTY RETAIL STORES                     5563077.11
AMERICAN AIRLINES                                             5296951.04
BUSINESS SERVICES NOT ELSEWHERE CLASSIFIED                    5218792.40
STATIONERY, OFFICE SUPPLIES, PRINTING AND WRITING PAPER       5094192.25
DIRCT MARKETING/DIRCT MARKETERS--NOT ELSEWHERE CLASSIFIED     4731575.15
OTHER FEES                                                    4076934.79
Name: Amount, dtype: float64

In [95]:
# # Create a set of dummy variables from the sex variable
# # dat = pd.get_dummies(data['Cardholder Last Name'])
# # Join the dummy variables to the main dataframe
# # df_new = pd.concat([df, df_sex], axis=1)
# # df_new

# from time import time
# import matplotlib.pyplot as plt

# from sklearn import metrics
# from sklearn.cluster import KMeans

# X_train = data['Amount']
# print X_train

# X = data.iloc[:,:-1]
# print X
# kmeans = KMeans(init='k-means++', n_clusters=10, n_init=10)
# kmeans.fit(X_train)

In [94]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

Amount_scaled = StandardScaler().fit_transform(data['Amount'].values.reshape(-1, 1))

kmeans = KMeans(init='k-means++', n_clusters=5, n_init=10).fit(Amount_scaled)
kmeans.labels_
kmeans.cluster_centers_

array([[  8.99317053e+00],
       [ -1.25961667e-02],
       [  3.46851436e+02],
       [  5.54345464e+01],
       [  1.74573951e+02]])

In [107]:
data['Amount'].nlargest(10)

# data['Cardholder First Initial']._get_numeric_data()
# 'Cardholder First Initial','Merchant Category Code (MCC)','Amount'
new_datas = data.filter(['Cardholder Last Name'], axis=1)

# new_datas[~new_datas.applymap(np.isreal).all(1)]

       Cardholder Last Name
0                     Mason
1                     Mason
2                    Massey
3                    Massey
4             Mauro-Herrera
5             Mauro-Herrera
6                      Mays
7                      Mays
8                  McCarthy
9                   McClurg
10                  McGowin
11                    McKee
12                 McLemore
13                  McMurry
14                   Meints
15                Mohiuddin
16                Mohiuddin
17                Mohiuddin
18              Mollenhauer
19               MONTGOMERY
20                  Morales
21                  Morales
22                    Fokar
23                  Forquer
24                  Forquer
25                     Foye
26                     Foye
27                      Fry
28                     Gage
29                     Gann
...                     ...
442428              Nikolai
442429              Nikolai
442430              Nikolai
442431              Nikolai
442432               Prince
442433             Ragsdale
442434               Stroup
442435               Stroup
442436               Stroup
442437               Stroup
442438               Stroup
442439               Stroup
442440               Stroup
442441              Wheeler
442442           Cardholder
442443           Cardholder
442444           Cardholder
442445           Cardholder
442446           Cardholder
442447           Cardholder
442448           Cardholder
442449           Cardholder
442450           Cardholder
442451           Cardholder
442452           Cardholder
442453           Cardholder
442454           Cardholder
442455           Cardholder
442456           Cardholder
442457           Cardholder

[442458 rows x 1 columns]

In [93]:
from time import time
import numpy as np
import matplotlib.pyplot as plt

from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn.datasets import load_digits
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale

reduced_data = PCA(n_components=0.1).fit_transform(Amount_scaled)
kmeans = KMeans(init='k-means++', n_clusters=5, n_init=10)
kmeans.fit(reduced_data)

# Step size of the mesh. Decrease to increase the quality of the VQ.
h = .02     # point in the mesh [x_min, x_max]x[y_min, y_max].

# Plot the decision boundary. For that, we will assign a color to each
x_min, x_max = reduced_data[:, 0].min() - 1, reduced_data[:, 0].max() + 1
y_min, y_max = reduced_data[:, 1].min() - 1, reduced_data[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))

# Obtain labels for each point in mesh. Use last trained model.
Z = kmeans.predict(np.c_[xx.ravel(), yy.ravel()])

# Put the result into a color plot
Z = Z.reshape(xx.shape)
plt.figure(1)
plt.clf()
plt.imshow(Z, interpolation='nearest',
           extent=(xx.min(), xx.max(), yy.min(), yy.max()),
           cmap=plt.cm.Paired,
           aspect='auto', origin='lower')

plt.plot(reduced_data[:, 0], reduced_data[:, 1], 'k.', markersize=2)
# Plot the centroids as a white X
centroids = kmeans.cluster_centers_
plt.scatter(centroids[:, 0], centroids[:, 1],
            marker='x', s=169, linewidths=3,
            color='w', zorder=10)
plt.title('K-means clustering on the digits dataset (PCA-reduced data)\n'
          'Centroids are marked with white cross')
plt.xlim(x_min, x_max)
plt.ylim(y_min, y_max)
plt.xticks(())
plt.yticks(())
plt.show()

IndexError: index 1 is out of bounds for axis 1 with size 1